services:
  postgres:
    image: postgres:16
    container_name: rinflow_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "9001:5432"
    volumes:
      - rinflow_postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rinflow_backend
    restart: on-failure
    depends_on:
      - postgres
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: rinflow_postgres
      DB_PORT: "5432"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app:cached
      - ./static:/static
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       VITE_API_BASE_URL: "http://localhost:5000"
  #   container_name: rinflow_frontend
  #   restart: on-failure
  #   depends_on:
  #     - backend
  #   environment:
  #     - VITE_API_BASE_URL=http://localhost:5000
  #   ports:
  #     - "5173:80"

volumes:
  rinflow_postgres_data: